# -*- coding: utf-8 -*-
"""teste_api

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Jx1eo_59ixbwsLtjoYQPgpsNmHMHU3g
"""

import requests

class BuscaEndereco:

    def __init__(self, cep):
        cep = str(cep)
        if self.cep_eh_valido(cep):
            self.cep = cep

        else:
            raise ValueError("CEP Inválido")

    def __str__(self):
        return self.mascara_cep()

    def cep_eh_valido(self,cep):
        if len(cep) == 8:
            return True
        else:
            return False

    def mascara_cep(self):
        cep_formatado = "{}-{}".format(self.cep[:5],self.cep[5:8])
        cep_formatado = str(cep_formatado)
        return cep_formatado

    def acesso_cep(self):
      url =requests.get("https://viacep.com.br/ws/{}/json/".format(self.cep))
      #return url.text
      dados = url.json()
      return ( dados['uf'], dados['localidade'], dados['bairro'], dados['complemento'])

import requests

cep = 96780032

obj_cep = BuscaEndereco(cep)

print(obj_cep)

estado,cidade,bairro,complmento = obj_cep.acesso_cep()
print(estado,"-",cidade,"-", bairro,"-",complmento)