# -*- coding: utf-8 -*-
"""lista_collections

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pX7IRuNcd36Qk2k1LjKoQv09QnGhF6_n
"""

class Conta:
    def __init__(self, nome, codigo, saldo):
        self._nome = nome
        self._codigo = codigo
        self._saldo = saldo

    def deposita(self,valor):
        self._saldo += valor
        print(self._saldo)

    def __str__(self):
        return "[ Código:{} - Nome: {} - Saldo: {:.2f}]".format(self._codigo,self._nome,  self._saldo)

    def __lt__(self,outro):
      if self._saldo != outro._saldo:
        return self._saldo < outro._saldo
      else:
        return self._codigo < outro._codigo

    def extrai_saldo(self):
        return self._saldo

    def vira_mes(self):
      self._saldo -= 2

from operator import attrgetter
conta_apeiron = Conta("Apeiron",40,5000)
conta_vini = Conta("Vini", 27,4700)
conta_levi = Conta("Levi", 15,5000)
contas = [conta_apeiron,conta_levi ,conta_vini]
conta_vini.deposita(300)

def extrai_saldo(self):
        return self._saldo

for conta in sorted(contas, key=attrgetter("_saldo","_codigo"), reverse=True):
  print(conta)

conta_apeiron.extrai_saldo()

conta_levi < conta_apeiron

