# -*- coding: utf-8 -*-
"""Collections_02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BB-NbQDic8aaF6InCOealfK67IY5AsWa
"""

houston ="Apollo 11 Base Tranquilidade a Aguia Pousou apollo"
houston = houston.lower()
houston = houston.split()


aparicoes = {}

for palavra in houston:
  ate_agora = aparicoes.get(palavra, 0)
  aparicoes[palavra] = ate_agora + 1

aparicoes

from collections import defaultdict

aparicoes = defaultdict(int)

for palavra in houston:
  aparicoes[palavra] += 1
  
aparicoes

from collections import Counter
aparicoes = Counter(houston)
aparicoes