# -*- coding: utf-8 -*-
"""Continuando com Collections

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLi6cvdGNEnCtGZZl4nuuH2C7oiCmkFK
"""

usuarios_curso_edicao = [27,14,32,56]
usuarios_curso_marketing = [12,34,45,56]
usuarios_curso_edicao
formacao_video_mark = []
formacao_video_mark = usuarios_curso_edicao.copy()
formacao_video_mark.extend(usuarios_curso_marketing)

set(formacao_video_mark)

lista_curso = list(formacao_video_mark)
sorted(lista_curso)

usuarios_curso_edicao = {27,34,14,32,56}
usuarios_curso_marketing = {12,34,45,56}

usuarios_curso_edicao | usuarios_curso_marketing # or

usuarios_curso_edicao & usuarios_curso_marketing # and

usuarios_curso_edicao - usuarios_curso_marketing

usuarios_curso_edicao ^ usuarios_curso_marketing # or exclusive

usuarios = {27,34,14,32,56}
usuarios.add(12)
usuarios

usuarios = {27,34,14,32,56}
usuarios = frozenset(usuarios)
usuarios

houston ="Apollo 11 base tranquilidade a aguia pousou"
set(houston.split())

aparicoes = {
  "Vini" : 3,
  "cachorro" : 2,
  "nome" : 2,
  "vindo" : 1
}

aparicoes["Vini"]

aparicoes["Sukhoi"] = 30 
aparicoes

del aparicoes["Sukhoi"]
aparicoes

"jaeger" in aparicoes
aparicoes["jaeger"] = 4

for elemento in aparicoes:
  print(elemento)

for elemento in aparicoes.keys():
  print(elemento)

for elemento in aparicoes.values():
  print(elemento)