# -*- coding: utf-8 -*-
"""Continuando com Collections

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLi6cvdGNEnCtGZZl4nuuH2C7oiCmkFK
"""

usuarios_curso = []