# -*- coding: utf-8 -*-
"""lista_conta .py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ul9f2VSnprhd2UayjYJ_1Z3Cw-TGPGDh
"""

class ContaCorrente:
    def __init__(self,nome, codigo, saldo):
        self.nome = nome
        self.codigo = codigo
        self.saldo = saldo

    def deposita(self,valor):
        self.saldo += valor
        print(self.saldo)

    def __str__(self):
        return "[Nome: {} - Código: {} - Saldo: {}]".format(self.nome, self.codigo,self.saldo)

    def adiciona_100(contas):
        for conta in contas:
            conta.deposita(100)

def adiciona_100(contas):
        for conta in contas:
            conta.deposita(100)

conta_apeiron = ContaCorrente("Apeiron",40,150)
conta_vini = ContaCorrente("Vini",27,2000)
contas = [conta_apeiron, conta_vini]

adiciona_100(contas)
print(contas[1])
print(contas[0])


contas.insert(0,54)

print(contas[0], contas[1], contas[2])

contas.insert(0,27)

print(contas[0], contas[1], contas[2])

adiciona_100(contas)

