# -*- coding: utf-8 -*-
"""lista_collections

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pX7IRuNcd36Qk2k1LjKoQv09QnGhF6_n
"""

class Conta:
    def __init__(self, nome, codigo, saldo):
        self._nome = nome
        self._codigo = codigo
        self._saldo = saldo

    def deposita(self,valor):
        self._saldo += valor
        print(self._saldo)

    def __str__(self):
        return "[ Código:{} - Nome: {} - Saldo: {:.2f}]".format(self._codigo,self._nome,  self._saldo)

    def extrai_saldo(self):
        return self._saldo

class ContaCorrente(Conta):
    def vira_mes(self):
      self._saldo -= 2

class ContaPoupanca(Conta):
    def vira_mes(self):
      self._saldo *= 1.01
      self._saldo -=3

conta_apeiron = ContaCorrente("Apeiron",40,150)
conta_vini = ContaCorrente("Vini", 27,1500)
contas = [conta_apeiron, conta_vini]
conta_vini.deposita(300)

def extrai_saldo(self):
        return self._saldo

for conta in sorted(contas, key=extrai_saldo):
  print(conta)

conta_apeiron.extrai_saldo()

