# -*- coding: utf-8 -*-
"""python testes .py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14XdnRZCH4QiGQUIS0E9sDHcM1xyyENO8
"""

x = 9875 % 10



print(x)

x = 9875 // 10

resto = x % 10

print(resto)